
logout:
  path: /logout
  methods: GET
questionnaire_get:
  path: /questionnaire/{slug}
  defaults:
    slug: flat
  methods: GET
  controller: App\Controller\QuestionnaireController::show
questionnaire_post:
  path: /questionnaire/{slug}
  methods: POST
  controller: App\Controller\QuestionnaireController::formSubmission
